---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo
  namespace: dlopez
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBSFbz7Zd9DiIyV1Ozd861/wtDBeuSjHB9a/1Mvxjmy5BRBmHMMEvnmK1CMmdV0C1ArzajmX7/1M4F2yN5H7AzEdlPD+Meu7AJriI1fyy/PeP8vuizdcmq5kelkiRZWV0eeZsY5RI5hHgpbcq3UPdKS/XV2jy9vQjMNzsarP+/nsmtQRsaQ6pZHtsYoaYRtq6qh6nyFjk2TmQN3QYmGBhpeFpf2Ak5XWDthR+VoZhHwLBznp1EiOi+HmLFZg3hHmjZdZ4qemp+mo1uIJ14hWuWIKHZjCvUNBpQRv/dGXTa7TSc7W6f1pip8bdRhSCyBOBXxnD0AxbZaV4PBiwqZs1LX3LIODkZs4yVhMNb5BPN/hzNI4l8JFkrAJDwuiunioXzMHPF8t9sY9Ar5zHmiOPOsh4tVOchRGVxdnbVFpH0R7I7QLp7FSLOYo+KHk96Bitc3wlut+kHMkpVIGzS38TMFzieiUEJv63IBWrZt5fPP1FcN/HkHbhCSsE1FOWz1wXdyhvoYomqTBUbXZOGKhpgB+Xyw455jvLFcwhChtH6WZAtAXEQhCrknWmxULTaQorbMDRi0bGHUdEfE6LDEPorxG2nFE4Zxw9mIZKJ97JDNWqQeQe0CC8boYHVKX1jsOfMf5Gzv3eGIJjkiJMbLY9b20iiDYU9LoVmPCk5tEngOpNtYJucXMoPlnTF0MD4BxFVkXphLtpiR
    MONGO_INITDB_ROOT_USERNAME: AgBn8kndikjVkgPRfRjWnYB0EqY9ucGocLkR+kYzgjJPQBiCpF90TXvbtuO7DOzenP81QMp7oNOIp/a78IiGxvWFLrHNTpnZ0YY9iy020D+ZAk6if2XJikcy3haF8xzVHpZUrbFqM6omImWW4+orgGLZbYcCFvCDHtovlSX1QdylYWAEhcjvGOWQ1VZTd4jsD5Yvfp7sdA0VAwJ78S/sR0AtpYe7H2lZycsW3u3Yl6FjW9tS2PAIKoUes09bZNiY5iEzSiB9/BsvwQQ+7oVFRbFWEdB201Zkt5yetiKDB20pq7WLFjyHAsR4+Nzh5pCJ0hBtO/b72mvPjqm9EWcLHQ8LnfFVERBRGmXw2SlMgoLVLH/72Pec1n7ruy/lwdmCwrhSp3yOyYv+Q7PEw3syk5ZRvs0T5FXrWypfP6AM8EmBX+QbVv4baNdWHLzRgzY5REE6xVImQOEd+6+xJ0G94Gi626ci220aMLqnkdJxeuidaEEcuSgLte6PQRF349ENpu4aabDX/g+HY+7PXQZMicGg/t2TTWqhA5jQdZt0mLNURs3tQ8T4hORmdT/PwFstfLx9vwmE7E4o8Z0q4N6sxqWRL+TlRuQ9pSFvK4gzarEqGP1W1kY35H1nlm+Bp4WrTnvYOU/2BxVddj+SOqzrx3pM4w3qb316x5LfSGen3BYzKwlFczQGwbo/1vBJqM+RZSMwBvz5
  template:
    metadata:
      creationTimestamp: null
      name: mongo
      namespace: dlopez
    type: Opaque
